baloons.push("Ellen", "Ciao!", "ellen")
baloons.push("Ellen", "Purtroppo la mini-demo finisce qui!", "ellen")
baloons.push("Ellen", "Se ti è piaciuta seguici su Facebook!", "ellen")
baloons.push("Ellen", "Se vuoi comprare una copia scontata in early access supportaci nella nostra campagna indiegogo!", "ellen")
baloons.push("Ellen", "Useremo tutti i soldi per produrre asset grafici all'altezza", "ellen")
baloons.push("Ellen", "e finiremo il primo capitolo della storia di Ellen.", "ellen")
baloons.push("Ellen", "Grazie mille e a presto!", "ellen")
