# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(549, 1031)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.treeWidget = QtWidgets.QTreeWidget(self.splitter)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.texturesTab = QtWidgets.QWidget()
        self.texturesTab.setObjectName("texturesTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.texturesTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.texturesFilter = QtWidgets.QLineEdit(self.texturesTab)
        self.texturesFilter.setObjectName("texturesFilter")
        self.verticalLayout_2.addWidget(self.texturesFilter)
        self.label = QtWidgets.QLabel(self.texturesTab)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.texturePool = QtWidgets.QListWidget(self.texturesTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.texturePool.sizePolicy().hasHeightForWidth())
        self.texturePool.setSizePolicy(sizePolicy)
        self.texturePool.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.texturePool.setTabKeyNavigation(False)
        self.texturePool.setTextElideMode(QtCore.Qt.ElideLeft)
        self.texturePool.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.texturePool.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.texturePool.setResizeMode(QtWidgets.QListView.Fixed)
        self.texturePool.setViewMode(QtWidgets.QListView.ListMode)
        self.texturePool.setUniformItemSizes(True)
        self.texturePool.setObjectName("texturePool")
        self.verticalLayout_2.addWidget(self.texturePool)
        self.tabWidget.addTab(self.texturesTab, "")
        self.charactersTab = QtWidgets.QWidget()
        self.charactersTab.setObjectName("charactersTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.charactersTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.characterPool = QtWidgets.QListWidget(self.charactersTab)
        self.characterPool.setObjectName("characterPool")
        self.verticalLayout_3.addWidget(self.characterPool)
        self.tabWidget.addTab(self.charactersTab, "")
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 549, 32))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuMap = QtWidgets.QMenu(self.menubar)
        self.menuMap.setObjectName("menuMap")
        self.menuGrid = QtWidgets.QMenu(self.menubar)
        self.menuGrid.setObjectName("menuGrid")
        MainWindow.setMenuBar(self.menubar)
        self.actionScene = QtWidgets.QAction(MainWindow)
        self.actionScene.setObjectName("actionScene")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionNew_2 = QtWidgets.QAction(MainWindow)
        self.actionNew_2.setObjectName("actionNew_2")
        self.actionSave_Scene = QtWidgets.QAction(MainWindow)
        self.actionSave_Scene.setObjectName("actionSave_Scene")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        self.actionRefresh.setObjectName("actionRefresh")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPPL = QtWidgets.QAction(MainWindow)
        self.actionPPL.setCheckable(True)
        self.actionPPL.setChecked(False)
        self.actionPPL.setObjectName("actionPPL")
        self.actionToonShading = QtWidgets.QAction(MainWindow)
        self.actionToonShading.setCheckable(True)
        self.actionToonShading.setObjectName("actionToonShading")
        self.actionAmbientOcclusion = QtWidgets.QAction(MainWindow)
        self.actionAmbientOcclusion.setCheckable(True)
        self.actionAmbientOcclusion.setObjectName("actionAmbientOcclusion")
        self.actionEdit_onLoad = QtWidgets.QAction(MainWindow)
        self.actionEdit_onLoad.setObjectName("actionEdit_onLoad")
        self.actionEdit_onUnload = QtWidgets.QAction(MainWindow)
        self.actionEdit_onUnload.setObjectName("actionEdit_onUnload")
        self.actionSet_background_image = QtWidgets.QAction(MainWindow)
        self.actionSet_background_image.setObjectName("actionSet_background_image")
        self.actionAdd_column = QtWidgets.QAction(MainWindow)
        self.actionAdd_column.setObjectName("actionAdd_column")
        self.actionAdd_row = QtWidgets.QAction(MainWindow)
        self.actionAdd_row.setObjectName("actionAdd_row")
        self.actionRemove_column = QtWidgets.QAction(MainWindow)
        self.actionRemove_column.setObjectName("actionRemove_column")
        self.actionRemove_row = QtWidgets.QAction(MainWindow)
        self.actionRemove_row.setObjectName("actionRemove_row")
        self.menuFile.addAction(self.actionNew_2)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave_Scene)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuMap.addAction(self.actionEdit_onLoad)
        self.menuMap.addAction(self.actionEdit_onUnload)
        self.menuGrid.addAction(self.actionSet_background_image)
        self.menuGrid.addSeparator()
        self.menuGrid.addAction(self.actionAdd_column)
        self.menuGrid.addAction(self.actionAdd_row)
        self.menuGrid.addSeparator()
        self.menuGrid.addAction(self.actionRemove_column)
        self.menuGrid.addAction(self.actionRemove_row)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMap.menuAction())
        self.menubar.addAction(self.menuGrid.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PandaRPG Engine Editor"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Tools"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Texturing"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "add texture to ground"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "clear textures"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Objects"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "add object with texture in tile"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "Lightning"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "add Light"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "Character"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "add character"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.texturesFilter.setPlaceholderText(_translate("MainWindow", "filter string"))
        self.label.setText(_translate("MainWindow", "Image preview..."))
        self.texturePool.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.texturesTab), _translate("MainWindow", "Textures"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.charactersTab), _translate("MainWindow", "Characters"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuMap.setTitle(_translate("MainWindow", "Map"))
        self.menuGrid.setTitle(_translate("MainWindow", "Grid"))
        self.actionScene.setText(_translate("MainWindow", "Scene"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionNew_2.setText(_translate("MainWindow", "New"))
        self.actionSave_Scene.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh"))
        self.action.setText(_translate("MainWindow", "Visit website..."))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionPPL.setText(_translate("MainWindow", "PerPixel Lighting"))
        self.actionToonShading.setText(_translate("MainWindow", "Toon Shading"))
        self.actionAmbientOcclusion.setText(_translate("MainWindow", "Ambient Occlusion"))
        self.actionEdit_onLoad.setText(_translate("MainWindow", "Edit onLoad()"))
        self.actionEdit_onUnload.setText(_translate("MainWindow", "Edit onUnload()"))
        self.actionSet_background_image.setText(_translate("MainWindow", "Set background image"))
        self.actionAdd_column.setText(_translate("MainWindow", "Add column"))
        self.actionAdd_row.setText(_translate("MainWindow", "Add row"))
        self.actionRemove_column.setText(_translate("MainWindow", "Remove column"))
        self.actionRemove_row.setText(_translate("MainWindow", "Remove row"))
