if persistence.load("luigi_salotto_leave")==0:
	baloons.push('Luigi', 'Oh! Ma chi si vede!', 'luigi')
	baloons.push('Luigi', 'E\' quasi ora di pranzo, ci dai una mano?', 'luigi')
	baloons.push('Ellen', 'No mi dispiace non posso.', 'ellen')
	baloons.push('Luigi', 'Ok, nessun problema.', 'luigi')
	baloons.push('Luigi', 'Puoi vedere un po\' di tv nel frattempo.', 'luigi')
	baloons.push('Luigi', 'Fai come se fossi a casa tua.', 'luigi')
	baloons.push('Ellen', '.....', 'ellen')
	baloons.push('Ellen', 'No guarda, mi dispiace ma ho un impegno improvviso.', 'ellen')
	baloons.push('Ellen', 'Non posso proprio rimanere, devo andare.', 'ellen')
	baloons.push('Luigi', 'Non ci credo.', 'luigi')
	baloons.push('Luigi', 'Che impegni puoi avere oggi?', 'luigi')
	baloons.push('Ellen', 'Eh- I miei genitori vorrebbero...', 'ellen')
	baloons.push('Ellen', 'Devo studiare sono in ritardo-', 'ellen')
	baloons.push('Luigi', 'In che senso?', 'luigi')
	baloons.push('Ellen', 'Non posso proprio rimanere mi dispiace.', 'ellen')
	baloons.push('Luigi', 'Posso aiutarti in qualche modo?', 'luigi')
	baloons.push('Luigi', 'Posso accompagnarti alla fermata?', 'luigi')
	baloons.push('Ellen', 'No tranquillo, non c\'è problema.', 'ellen')
	baloons.push('Luigi', 'Davvero, mi farebbe piacere.', 'luigi')
	baloons.push('Ellen', 'Sul serio farò due passi.', 'ellen')
	baloons.push('Ellen', 'Mi farà bene.', 'ellen')
	baloons.push('Luigi', 'Se è questo che vuoi.', 'luigi')
	baloons.push('Luigi', 'Mi dispiace tu debba già andare.', 'luigi')
	baloons.push('Ellen', 'Anche a me.', 'ellen')
	baloons.push('Ellen', 'Ci... Ci vedremo più avanti dai.', 'ellen')
	baloons.push('Ellen', 'Come sempre.', 'ellen')
	baloons.push('Luigi', 'Allora buon viaggio!', 'luigi')
	baloons.push('Ellen', 'Grazie! A presto!', 'ellen')

	persistence.save("luigi_salotto_leave", 1)
elif persistence.load("luigi_salotto_leave")==1:
	baloons.push('Luigi', 'Ma sei davvero sicura di voler andare?', 'luigi')
	baloons.push('Luigi', 'Resta pure quanto vuoi.', 'luigi')
	baloons.pushThought('Ellen', 'Non posso restare. Kate mi odia.', 'ellen')
	baloons.push('Ellen', 'Mi dispiace. Ho davvero... molti impegni.', 'ellen')
	baloons.push('Ellen', 'Grazie comunque.', 'ellen')
	persistence.save("luigi_salotto_leave", 2)
elif persistence.load("luigi_salotto_leave")==2:
	baloons.push('Luigi', 'Allora buon viaggio.', 'luigi')
	baloons.push('Ellen', 'Grazie.', 'ellen')
