if persistence.load("luigi_salotto_leave")==0:
	baloons.push('Luigi', 'E\' quasi ora di pranzo, ci dai una mano?', 'luigi')
	baloons.push('Ellen', 'No mi dispiace non posso.', 'ellen')
	baloons.push('Luigi', 'Ok, nessun problema.', 'luigi')
	baloons.push('Luigi', 'Fai come se fossi a casa tua.', 'luigi')
	baloons.push('Ellen', '.....', 'ellen')
	baloons.push('Ellen', 'Non posso proprio rimanere, devo andare.', 'ellen')
	baloons.push('Luigi', 'Posso aiutarti in qualche modo?', 'luigi')
	baloons.push('Luigi', 'Posso accompagnarti alla fermata?', 'luigi')
	baloons.push('Ellen', 'No tranquillo, non c\'è problema.', 'ellen')
	baloons.push('Ellen', 'Farò due passi. Mi farà bene.', 'ellen')
	baloons.push('Luigi', 'Mi dispiace...', 'luigi')
	baloons.push('Ellen', 'Anche a me.', 'ellen')
	baloons.push('Luigi', 'Allora buon viaggio!', 'luigi')
	baloons.push('Ellen', 'Grazie! A presto!', 'ellen')

	persistence.save("luigi_salotto_leave", 1)
elif persistence.load("luigi_salotto_leave")==1:
	baloons.push('Luigi', 'Sei davvero sicura di voler andare?', 'luigi')
	baloons.push('Luigi', 'Abbiamo i marshmallow.', 'luigi')
	baloons.pushThought('Ellen', 'Non posso restare. Kate mi odia.', 'ellen')
	baloons.push('Ellen', 'Mi dispiace. Ho davvero... molti impegni.', 'ellen')
	baloons.push('Ellen', 'Grazie comunque.', 'ellen')
	persistence.save("luigi_salotto_leave", 2)
elif persistence.load("luigi_salotto_leave")==2:
	baloons.push('Luigi', 'Allora buon viaggio.', 'luigi')
	baloons.push('Ellen', 'Grazie.', 'ellen')
