audioManager.stopLongEffect('wind')
audioManager.stopLongEffect('birds')
audioManager.playEffect('sfx/closed_door.ogg')
audioManager.playLongEffect('carengine', 'sfx/carengine.ogg')

taskMgr.doMethodLater(5, baloons.pushThought, 'selfspeak', extraArgs = ["Ellen","Ho bisogno di un buon caffè caldo.","ellen"])
taskMgr.doMethodLater(15, baloons.pushThought, 'selfspeak', extraArgs = ["Ellen","Perchè non ha mai detto quello che pensava di me sin dall'inizio?","ellen"])
taskMgr.doMethodLater(25, baloons.pushThought, 'selfspeak', extraArgs = ["Ellen","Pensa che ci stia male solo lei?","ellen"])
taskMgr.doMethodLater(35, baloons.pushThought, 'selfspeak', extraArgs = ["Ellen","E poi sarei io l'egocentrica!","ellen"])
taskMgr.doMethodLater(36, baloons.pushThought, 'selfspeak', extraArgs = ["Ellen","Le sue parole mi hanno attraversato il cuore da parte a parte e ora sento il dolore uscire OVUNQUE.","ellen"])
taskMgr.doMethodLater(37, baloons.pushThought, 'selfspeak', extraArgs = ["Ellen","Ellen ora basta.","ellen"])
taskMgr.doMethodLater(38, baloons.pushThought, 'selfspeak', extraArgs = ["Ellen","Smettila di pensare altrimenti diventi paranoica.","ellen"])
taskMgr.doMethodLater(50, baloons.pushThought, 'selfspeak', extraArgs = ["Ellen","Devi distrarti.","ellen"])
taskMgr.doMethodLater(55, baloons.pushThought, 'selfspeak', extraArgs = ["Ellen","dove ho messo quel cd... doveva essere sotto il sedile... ma qua...","ellen"])
taskMgr.doMethodLater(60, baloons.pushThought, 'selfspeak', extraArgs = ["Ellen","non c'è nulla... meglio dar un occhiata dopo altrimenti rischio un inci... Merda!","ellen"])
taskMgr.doMethodLater(64, messenger.send, 'accepting message', extraArgs = ["space"])
taskMgr.doMethodLater(64, messenger.send, 'accepting message', extraArgs = ["space"])
taskMgr.doMethodLater(64, messenger.send, 'accepting message', extraArgs = ["space"])
taskMgr.doMethodLater(65, messenger.send, 'accepting message', extraArgs = ["space"])
taskMgr.doMethodLater(65, messenger.send, 'accepting message', extraArgs = ["space"])
taskMgr.doMethodLater(65, audioManager.stopMusic, 'stopping music', extraArgs = [0.1])
taskMgr.doMethodLater(65, audioManager.stopLongEffect, 'stopping music', extraArgs = ['carengine'])
taskMgr.doMethodLater(65, audioManager.playEffect, 'stopping music', extraArgs = ['sfx/caraccident.ogg'])
taskMgr.doMethodLater(65, messenger.send, 'changeMap', extraArgs = ["changeMap", ['incidente.map','20,11']])
