baloons.pushThought("Ellen","Ugh...","ellen")
baloons.pushThought("Ellen","Sono...","ellen")
baloons.pushThought("Ellen","morta?","ellen")
baloons.pushThought("Ellen","Devo chiamare....","ellen")
baloons.pushThought("Ellen","...q...qualcuno...","ellen")
baloons.push("Ellen","A...","ellen")
baloons.push("Ellen","Ai...","ellen")
baloons.pushThought("Ellen","Devo... devo... farcela...","ellen")
baloons.push("Ellen","Aiu-","ellen")
baloons.pushThought("Ellen","Non si muove più...","ellen")
baloons.pushThought("Ellen","...","ellen")
baloons.pushThought("Ellen","Fa... freddo...","ellen")
baloons.pushThought("Ellen","Molto... freddo...","ellen")
baloons.pushThought("Ellen","Kate...","ellen")
baloons.pushThought("Ellen","Kate...","ellen")
baloons.pushThought("Ellen","A..i...u...-","ellen", 0.5)
baloons.pushThought("Ellen","----","ellen", 0.6)
audioManager.playLongEffect('wind', 'sfx/wind_town.ogg')
audioManager.playLongEffect('birds', 'sfx/birds_chirp.ogg')
