def blackOnEmptyMessages():
    if persistence.load("blackstate")==0:
        persistence.save("blackstate", 1)
        messenger.send('changeMap', ['black.map','5,5'])
    elif persistence.load("blackstate")==1:
        persistence.save("blackstate", 2)
        messenger.send('changeMap', ['black.map','5,5'])

if persistence.load("blackstate")==0:
    taskMgr.doMethodLater(1.01, baloons.push, 'selfspeak', extraArgs = ["Escursionista","Non me ne andrò di qui fino a quando  non avrò visto almeno uno scoiattolo.","8x1"])
    taskMgr.doMethodLater(1.02, baloons.push, 'selfspeak', extraArgs = ["Escursionista 2","Seh...","8x6"])
    taskMgr.doMethodLater(1.03, baloons.push, 'selfspeak', extraArgs = ["Escursionista","Hai capito Livio?","8x1"])
    taskMgr.doMethodLater(1.04, baloons.push, 'selfspeak', extraArgs = ["Escursionista","Vedi di fartelo entrare in testa!","8x1"])
    taskMgr.doMethodLater(1.05, baloons.push, 'selfspeak', extraArgs = ["Escursionista 2","Seh...","8x6"])
    taskMgr.doMethodLater(1.06, baloons.pushThought, 'selfspeak', extraArgs = ["Escursionista 2","Lo sapevo che era meglio la gita aziendale...","8x6"])
    taskMgr.doMethodLater(1.07, baloons.push, 'selfspeak', extraArgs = ["Escursionista","Oh dio mio Livio! Corri qui!","6x2"])
    taskMgr.doMethodLater(1.08, baloons.push, 'selfspeak', extraArgs = ["Escursionista 2","Giuro che se è un altro sasso a forma di cuore io-","8x4"])
    taskMgr.doMethodLater(1.09, baloons.push, 'selfspeak', extraArgs = ["Escursionista 2","Oh cazzo! Stai bene?? Sei sveglia??","4x4"])
    taskMgr.doMethodLater(1.10, baloons.push, 'selfspeak', extraArgs = ["Escursionista","Non risponde!! Bisogna chiamare aiuto!","6x2"])
    taskMgr.doMethodLater(1.11, baloons.push, 'selfspeak', extraArgs = ["Escursionista 2","Pronto? Si? Pronto soccorso? Siamo...","4x4"])
    taskMgr.doMethodLater(1.12, baloons.push, 'selfspeak', extraArgs = ["Escursionista","Aiuto! Ci serve aiuto! Una ragazza sta male!!","6x2"])
    taskMgr.doMethodLater(1.13, baloons.push, 'selfspeak', extraArgs = ["Escursionista 2","Si... Si... Ha sentito si... Le mando le ... Si il soccorso... si lo paghiamo, ma mandate qualcuno perdio!!","4x4"])
    taskMgr.doMethodLater(1.14, baloons.push, 'selfspeak', extraArgs = ["Escursionista","Ho paura che stia morendo! Non è messa bene!","4x4"])
    taskMgr.doMethodLater(1.15, baloons.push, 'selfspeak', extraArgs = ["Escursionista 2","Sta- Sta morendo? Non morire!!","6x2"])
    taskMgr.doMethodLater(12, audioManager.playEffect, 'seffect', extraArgs = ['sfx/grass_steps.ogg'])
    taskMgr.doMethodLater(12.5, audioManager.playEffect, 'seffect', extraArgs = ['sfx/grass_steps.ogg'])
if persistence.load("blackstate")==1:
    audioManager.playEffect('sfx/ambulance.ogg')
    audioManager.playLongEffect('carengine', 'sfx/carengine.ogg')
    taskMgr.doMethodLater(6.5, audioManager.playMusic, 'smusic', extraArgs = ['soundtrack/teardrop.ogg'])
    baloons.push("Infermiere", "Le condizioni sono critiche dottore!", "2x7")
    baloons.push("Dottore", "Somministrate adrenalina, subito!", "2x1")
    baloons.push("Infermiere 2", "Adrenalina somministrata!", "6x7")
    baloons.pushThought("Ellen", "Cosa sta...", "4x4")
    baloons.push("Infermiere", "Non ci sono effetti. ...", "2x7")
    baloons.push("Infermiere 2", "Dottore... all'ospedale non ci arriveremo.", "6x7")
    baloons.push("Infermiere 2", "Dottore!", "6x7")
    baloons.pushThought("Ellen", "Devo parlare...", "4x4")
    baloons.push("Dottore", "Preparate la strumentazione per il coma farmacologico.", "2x1")
    baloons.push("Infermiere", "Siamo su un'ambulanza! Non funzionerà!", "2x7")
    baloons.push("Dottore", "Dobbiamo provare! È troppo giovane per andarsene così!", "2x1")
    baloons.pushThought("Ellen", "L'oblio...", "4x4")
    baloons.push("Infermiere", "Prepariamo.", "2x7")
    baloons.push("Infermiere 2", "Pronto in 5 secondi.", "6x7")
    baloons.pushThought("Ellen", "Aiuto Kate! Aiut...", "4x4")
    baloons.push("Infermiere 2", "Fatto!", "6x7")
    baloons.pushThought("Ellen", "Aiu...", "4x4")
    baloons.push("Dottore", "Non mi morire! Non oggi!", "2x1")
    baloons.push("Dottore", "..opri... che s... teva....ar......co.... ", "2x1")
    baloons.pushThought("Ellen", "Non sento più nie-", "4x4")
    baloons.push("Dottore", "..vi..-", "2x1")
    baloons.pushThought("Ellen", "---", "4x4")
if persistence.load("blackstate")==2:
    audioManager.stopLongEffect('carengine')
    baloons.pushThought("Ellen", "....", "4x4")
    baloons.pushThought("Ellen", "Una strada...", "4x4")
    baloons.pushThought("Ellen", "Un minimarket...", "4x4")
    baloons.pushThought("Ellen", "Cercavamo delle batterie...", "4x4")
    baloons.pushThought("Ellen", "Voleva che ballassimo il valzer...", "4x4")
    baloons.pushThought("Ellen", "...a mezzanotte in punto...", "4x4")
    baloons.pushThought("Ellen", "Abbiamo corso scalzi...", "4x4")
    baloons.pushThought("Ellen", "...era una tradizione...", "4x4")
    baloons.pushThought("Ellen", "Aveva vinto lei...", "4x4")
    baloons.pushThought("Ellen", "Non mi ricordo con chi ho ballato...", "4x4")
    baloons.pushThought("Ellen", "Non con lei...", "4x4")
    baloons.pushThought("Ellen", "Lei... non lo so...", "4x4")
    baloons.pushThought("Ellen", "Non mi ricordo di lei...", "4x4")
    baloons.pushThought("Ellen", "Ci siamo lanciati giù dalla montagna...", "4x4")
    baloons.pushThought("Ellen", "Eravamo tanti.", "4x4")
    baloons.pushThought("Ellen", "Paul era rimasto sotto...", "4x4")
    baloons.pushThought("Ellen", "L'ho confortato... non era importante...", "4x4")
    baloons.pushThought("Ellen", "Lei non mi parlava...", "4x4")
    baloons.pushThought("Ellen", "L'avevo già persa...", "4x4")
    baloons.pushThought("Ellen", "C'era un Pino sopra a una collina...", "4x4")
    baloons.pushThought("Ellen", "Ha fatto un discorso...", "4x4")
    baloons.pushThought("Ellen", "Ridevo a metà...", "4x4")
    baloons.pushThought("Ellen", "Era una via di fuga...", "4x4")
    baloons.pushThought("Ellen", "Tre giorni per capire quello che volevo...", "4x4")
    baloons.pushThought("Ellen", "Abbiamo visto un film...", "4x4")
    baloons.pushThought("Ellen", "Harry a pezzi...", "4x4")
    baloons.pushThought("Ellen", "Dio se ridevamo...", "4x4")
    baloons.pushThought("Ellen", "...io stavo in silenzio.", "4x4")
    baloons.pushThought("Ellen", "Guardavo il vuoto...", "4x4")
    baloons.pushThought("Ellen", "...nei suoi occhi.", "4x4")
    baloons.pushThought("Ellen", "Dovevo andare via.", "4x4")
    baloons.pushThought("Ellen", "Ero perso, guardavo l’orologio, era un momento che non sarebbe mai più tornato indietro, in qualche modo lo sapevo.", "4x4")
    baloons.pushThought("Ellen", "Non l’avrei più rivista", "4x4")
    baloons.pushThought("Ellen", "Arriva il momento di andare e ancora non parto.", "4x4")
    baloons.pushThought("Ellen", "Passa un minuto e in un lampo di crudele lucidità afferro un foglio bianco a quadretti e ci scrivo a matita", "4x4")
    baloons.pushThought("Ellen", "“ti voglio bene”", "4x4")
    baloons.pushThought("Ellen", "Lo metto sotto il suo cuscino.", "4x4")
    baloons.pushThought("Ellen", "Lei dice qualcosa, non ricordo cosa.", "4x4")
    baloons.pushThought("Ellen", "Io resto impietrito dalla paura.", "4x4")
    baloons.pushThought("Ellen", "… Lei mi abbraccia.", "4x4")
    baloons.pushThought("Ellen", "La lasciai volendole bene.", "4x4")
    baloons.pushThought("Ellen", "Ho perso questo.", "4x4")
    baloons.pushThought("Ellen", "È chiaro e lampante adesso.", "4x4")
    baloons.pushThought("Ellen", "Ed è incredibilmente irrecuperabile quanto irrilevante.", "4x4")
    baloons.pushThought("Ellen", "...", "4x4")
    baloons.pushThought("Ellen", "Tornai da Luis.", "4x4")
    baloons.pushThought("Ellen", "I giorni successivi sono stati un lento trascinarsi di apatia e rassegnazione.", "4x4")
    baloons.pushThought("Ellen", "Un tentativo disperato di rimettere a posto i pezzi", "4x4")
    baloons.pushThought("Ellen", "Di dimostrarle qualcosa alla quale lei ormai non avrebbe mai più creduto.", "4x4")
    baloons.pushThought("Ellen", "Mi trascina nell'abisso, più della morte.", "4x4")
    baloons.pushThought("Ellen", "L’ho ferita.", "4x4")
    baloons.pushThought("Ellen", "Per un istante mi è passato per la mente", "4x4")
    baloons.pushThought("Ellen", "Avrei dovuto.", "4x4")
    baloons.pushThought("Ellen", "O tutto o niente.", "4x4")
    baloons.pushThought("Ellen", "...", "4x4")
    baloons.pushThought("Ellen", "È stato il mio fallimento nel farmi capire", "4x4")
    baloons.pushThought("Ellen", "E la mia disperazione nel non esserci riuscito", "4x4")
    baloons.pushThought("Ellen", "Ferendo una persona che mi voleva bene.", "4x4")
    baloons.pushThought("Ellen", "Sono al capolinea, questo è quanto.", "4x4")
    baloons.pushThought("Ellen", "Sono pronta a morire.", "4x4")
    baloons.pushThought("Ellen", "...", "4x4")
taskMgr.doMethodLater(2, baloons.setOnEmptyCallback, 'setcallback', extraArgs = [blackOnEmptyMessages])
