baloons.push("Ellen", "Amy le farfalle vivono pochissimo.", "ellen")
baloons.push("Ellen", "Non avresti fatto in tempo nemmeno a portarla a casa che sarebbe morta.", "ellen")
baloons.push("Amy", "Non è vero!", "amy")
baloons.push("Ellen", "Si che è vero.", "ellen")
baloons.push("Amy", "No", "amy")
baloons.push("Ellen", "Si...", "ellen")
baloons.push("Amy", "Ho detto di no!", "amy")
baloons.push("Ellen", "Chiedilo alla mamma allora...", "ellen")
baloons.push("Amy", "Dopo lo farò di certo.", "amy")
baloons.push("Ellen", "Okey.", "ellen")
###pause
amy = pGrid.getObjectById("amy")
ellen = pGrid.getObjectById("ellen")
amy.npc_push_walk("right", 2)
amy.npc_push_walk("down", 2)
amy.npc_push_walk("left", 1)
###pause
baloons.push("Amy", "Ellen mi spingi?", "amy")
baloons.push("Ellen", "mh hm...", "ellen")
baloons.push("Amy", "Evviva, Ellen voglio arrivare a toccare le nuvole!!", "amy")
baloons.push("Ellen", "Chiedi troppo, inizia a spingerti da sola che finisco almeno questo capitolo...", "ellen")
baloons.push("Amy", "EH santo celo sei sempre con quel libro.", "amy")
baloons.push("Amy", "Cosa avrà di così speciale non lo so proprio!", "amy")
baloons.push("Ellen", "Non è un libro qualsiasi, è il romanzo rosa più bello mai pubblicato.", "ellen")
baloons.push("Amy", "Asociale", "amy")
baloons.push("Ellen", "Non sai nemmeno cosa significa...", "ellen")
baloons.push("Amy", "Si invece, l'ho chiesto alla mamma.", "amy")
baloons.push("Amy", "Significa che sprechi il tuo tempo a stare da sola.", "amy")
baloons.push("Ellen", "Amy, vuoi che ti venga a spingere si o no?", "ellen")
baloons.push("Amy", "Si!! Sto aspettando da ventimila ore...", "amy")
baloons.push("Ellen", "Bene, allora non voglio sentire più una parola uscire dalla tua bocca", "ellen")
baloons.push("Ellen", "fino a quando non ho finito di leggere.", "ellen")
baloons.push("Amy", "Non posso neanche...?", "amy")
baloons.push("Ellen", "NO!", "ellen")
baloons.push("Amy", "...", "amy")
baloons.push("Ellen", "Oh la! Finalmente un po di pace...", "ellen")
