persistence.save("canleave", "no")
audioManager.playEffect('sfx/closed_door.ogg')
audioManager.playLongEffect('wind', 'sfx/wind_town.ogg')
audioManager.playLongEffect('birds', 'sfx/birds_chirp.ogg')
baloons.pushThought("Ellen", "Le chiavi...", "ellen")
baloons.pushThought("Ellen", "Dove le ho messe?", "ellen")
taskMgr.doMethodLater(20, audioManager.playMusic, 'music', extraArgs = ["soundtrack/natsukusanokaori.ogg"])
taskMgr.doMethodLater(5, fadingtext.spawn, 'titles', extraArgs = ["Story and dialogues by:\n\nArianna Nicoletti"])
taskMgr.doMethodLater(15, fadingtext.spawn, 'titles', extraArgs = ["Lead Development:\n\nClaudio Desideri"])
taskMgr.doMethodLater(25, fadingtext.spawn, 'titles', extraArgs = ["Artworks by:\n\nLisa Marcuzzi\nDoris Berisonzi"])
taskMgr.doMethodLater(35, fadingtext.spawn, 'titles', extraArgs = ["Music by:\nLucas King\nFreesound.org"])
taskMgr.doMethodLater(10, baloons.pushThought, 'selfspeak', extraArgs = ["Ellen","Lascio un pezzo di me qui.","ellen"])
taskMgr.doMethodLater(30, baloons.pushThought, 'selfspeak', extraArgs = ["Ellen","Forse doveva succedere.","ellen"])
taskMgr.doMethodLater(40, baloons.pushThought, 'selfspeak', extraArgs = ["Ellen","È strano...","ellen"])
taskMgr.doMethodLater(41, baloons.pushThought, 'selfspeak', extraArgs = ["Ellen","È come se fossi alla fine di qualcosa.","ellen"])
taskMgr.doMethodLater(42, baloons.pushThought, 'selfspeak', extraArgs = ["Ellen","Forse è solo lo stress.","ellen"])
taskMgr.doMethodLater(75, baloons.pushThought, 'selfspeak', extraArgs = ["Ellen","Ecco le chiavi! È meglio andarsene.","ellen"])
taskMgr.doMethodLater(75, persistence.save, 'gamechanging', extraArgs = ['canleave', 'yes'])
